url0: https://www.doppiotech.com/

url00: file:///C:/Users/User/Desktop/Project/Code/Webautomate_Doppio/ep01/ex00.html

url01: file:///C:/Users/User/Desktop/Project/Code/Webautomate_Doppio/ep01/ex01.html

url02: file:///C:/Users/User/Desktop/Project/Code/Webautomate_Doppio/ep01/ex02.html

url03: file:///C:/Users/User/Desktop/Project/Code/Webautomate_Doppio/ep01/ex03.html

urlli04: file:///home/trcloud/Desktop/Coding/Dop/ep01/ex04.html